name: simple_data_class_generator
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  build:
  analyzer:
  source_gen:
  code_builder:
  dart_style:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
